version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: zanaya_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zanaya_user
      POSTGRES_PASSWORD: zanaya_pass
      POSTGRES_DB: zanaya_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
